
// Tabla: PROVEEDORES
CREATE TABLE Proveedores (
    id_proveedor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    nombre VARCHAR2(100) NOT NULL,
    telefono VARCHAR2(20),
    direccion VARCHAR2(255),
    CONSTRAINT PK_Proveedores PRIMARY KEY (id_proveedor)
);

// Tabla: CLIENTES
CREATE TABLE Clientes (
    id_cliente NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(50) NOT NULL,
    correo VARCHAR2(100),
    telefono VARCHAR2(20),
    CONSTRAINT PK_Clientes PRIMARY KEY (id_cliente)
);

// Tabla: EMPLEADOS
CREATE TABLE Empleados (
    id_empleado NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(50) NOT NULL,
    puesto VARCHAR2(50),
    salario NUMBER(10, 2), 
    fecha_contratacion DATE, 
    CONSTRAINT PK_Empleados PRIMARY KEY (id_empleado)
);

// Tabla: MENÚ
CREATE TABLE Menu (
    id_plato NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion CLOB, 
    precio_venta NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_Menu PRIMARY KEY (id_plato)
);



// Tabla: PRODUCTOS
CREATE TABLE Productos (
    id_producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(50),
    precio_compra NUMBER(10, 2),
    stock NUMBER(5) NOT NULL,
    id_proveedor NUMBER NOT NULL,
    CONSTRAINT PK_Productos PRIMARY KEY (id_producto),
    CONSTRAINT FK_Producto_Proveedor FOREIGN KEY (id_proveedor)
        REFERENCES Proveedores (id_proveedor)
);

// Tabla: PEDIDOS
CREATE TABLE Pedidos (
    id_pedido NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    fecha DATE,
    total NUMBER(10, 2),
    estado VARCHAR2(50) DEFAULT 'En Proceso' NOT NULL,
    id_cliente NUMBER NOT NULL,
    CONSTRAINT PK_Pedidos PRIMARY KEY (id_pedido),
    CONSTRAINT FK_Pedido_Cliente FOREIGN KEY (id_cliente)
        REFERENCES Clientes (id_cliente)
);

// Tabla: DETALLE_PEDIDO
CREATE TABLE Detalle_Pedido (
    id_detalle NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_pedido NUMBER NOT NULL,
    id_plato NUMBER NOT NULL,
    cantidad NUMBER(5) NOT NULL,
    subtotal NUMBER(10, 2),
    CONSTRAINT PK_DetallePedido PRIMARY KEY (id_detalle),
    CONSTRAINT FK_Detalle_Pedido FOREIGN KEY (id_pedido)
        REFERENCES Pedidos (id_pedido)
        ON DELETE CASCADE,
    CONSTRAINT FK_Detalle_Plato FOREIGN KEY (id_plato)
        REFERENCES Menu (id_plato)
);

// Tabla: FACTURAS
CREATE TABLE Facturas (
    id_factura NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_pedido NUMBER NOT NULL,
    fecha_emision DATE NOT NULL,
    monto_total NUMBER(10, 2),
    metodo_pago VARCHAR2(50),
    CONSTRAINT PK_Facturas PRIMARY KEY (id_factura),
    CONSTRAINT UQ_Factura_Pedido UNIQUE (id_pedido),
    CONSTRAINT FK_Factura_Pedido FOREIGN KEY (id_pedido)
        REFERENCES Pedidos (id_pedido)
);

