/* ===========================================================
   TRIGGERS - PROYECTO "DELICIAS DE ALTURA"
   Autores: Enzo Morales y Andrey Rodríguez
   Descripción: Automatización de procesos y control de integridad
   =========================================================== */

/*============================================================
  TRIGGER: ACTUALIZAR INVENTARIO AL INSERTAR DETALLE DE PEDIDO
  Reduce el stock del producto correspondiente al plato vendido
============================================================*/
CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_STOCK
AFTER INSERT ON Detalle_Pedido
FOR EACH ROW
DECLARE
    v_stock NUMBER;
BEGIN
    -- Disminuye el stock del producto asociado al plato
    SELECT stock INTO v_stock 
    FROM Productos 
    WHERE id_producto = :NEW.id_plato;

    v_stock := v_stock - :NEW.cantidad;

    UPDATE Productos
    SET stock = v_stock
    WHERE id_producto = :NEW.id_plato;
END;
/

/*============================================================
  TRIGGER: RECALCULAR TOTAL DE PEDIDO
  Cada vez que se inserta, actualiza o elimina un detalle,
  se recalcula el total del pedido
============================================================*/
CREATE OR REPLACE TRIGGER TRG_RECALCULAR_TOTAL_PEDIDO
AFTER INSERT OR UPDATE OR DELETE ON Detalle_Pedido
FOR EACH ROW
DECLARE
    v_total NUMBER;
BEGIN
    SELECT NVL(SUM(subtotal), 0)
    INTO v_total
    FROM Detalle_Pedido
    WHERE id_pedido = NVL(:NEW.id_pedido, :OLD.id_pedido);

    UPDATE Pedidos
    SET total = v_total
    WHERE id_pedido = NVL(:NEW.id_pedido, :OLD.id_pedido);
END;
/

/*============================================================
  TRIGGER: GENERAR FACTURA AUTOMÁTICA
  Al cambiar el estado del pedido a “Cerrado”,
  se genera la factura correspondiente.
============================================================*/
CREATE OR REPLACE TRIGGER TRG_GENERAR_FACTURA
AFTER UPDATE OF estado ON Pedidos
FOR EACH ROW
WHEN (NEW.estado = 'Cerrado')
DECLARE
    v_total NUMBER;
BEGIN
    SELECT total INTO v_total 
    FROM Pedidos 
    WHERE id_pedido = :NEW.id_pedido;

    INSERT INTO Facturas (id_pedido, fecha_emision, monto_total, metodo_pago)
    VALUES (:NEW.id_pedido, SYSDATE, v_total, 'Efectivo');
END;
/

/*============================================================
  TRIGGER: PREVENIR ELIMINACIÓN DE CLIENTES CON PEDIDOS
  Evita eliminar clientes que tengan pedidos registrados.
============================================================*/
CREATE OR REPLACE TRIGGER TRG_PREVENIR_BORRADO_CLIENTE
BEFORE DELETE ON Clientes
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count 
    FROM Pedidos 
    WHERE id_cliente = :OLD.id_cliente;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar cliente con pedidos existentes.');
    END IF;
END;
/

/*============================================================
  TRIGGER: AUDITORÍA DE CAMBIOS DE STOCK
  Registra en una tabla LOG_STOCK cada vez que cambia el stock.
============================================================*/

-- Crear tabla de auditoría si no existe
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE LOG_STOCK (
            id_log NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            id_producto NUMBER,
            stock_anterior NUMBER,
            stock_nuevo NUMBER,
            fecha_cambio DATE,
            usuario VARCHAR2(50)
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; END IF; -- Tabla ya existe
END;
/

-- Trigger de auditoría
CREATE OR REPLACE TRIGGER TRG_LOG_CAMBIO_STOCK
AFTER UPDATE OF stock ON Productos
FOR EACH ROW
BEGIN
    INSERT INTO LOG_STOCK (id_producto, stock_anterior, stock_nuevo, fecha_cambio, usuario)
    VALUES (:OLD.id_producto, :OLD.stock, :NEW.stock, SYSDATE, USER);
END;
/
